project.name: product-manager

spring:
  #Application
  application:
    name: cypher

  #Database - H2
  h2.console:
    enabled: true
    path: /h2
  datasource:
    url: jdbc:h2:mem:avenuecode-productmanager-marcopollivier
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialize: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
